app_id: "300579e3-4a79-4fd2-8f09-60ed83326dd6"
app_secret: "cGr7Q~2.qrIYO4EOBSG_H.VHmZFRVXcJ~gJle" 
test: "http://localhost:8000/server/getAToken/"
redirect: "http://localhost:8001/proccess/"
authority: "https://login.microsoftonline.com/common"
scopes:
    - user.read   
    - mailboxsettings.read
    - calendars.readwrite
    - authority
    - "https://login.microsoftonline.com/common"